services:
  nginx:
    container_name: nginx_compose
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 443:443
    environment:
      - AUDIOBOOKSHELF_HOSTNAME=${AUDIOBOOKSHELF_HOSTNAME}
      - GUACAMOLE_HOSTNAME=${GUACAMOLE_HOSTNAME}
      - HOST_IP=${HOST_IP}
